"""QQ

Revision ID: 29d15d666661
Revises: 
Create Date: 2019-11-02 00:15:38.296658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d15d666661'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allineamenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allineamento', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipologie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personaggi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('quantita', sa.Integer(), nullable=True),
    sa.Column('tipologia_id', sa.Integer(), nullable=True),
    sa.Column('allineamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['allineamento_id'], ['allineamenti.id'], ),
    sa.ForeignKeyConstraint(['tipologia_id'], ['tipologie.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personaggi')
    op.drop_table('tipologie')
    op.drop_table('allineamenti')
    # ### end Alembic commands ###
