"""empty message

Revision ID: 8cb3c41af4a3
Revises: 29d15d666661
Create Date: 2019-11-02 01:13:37.987137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb3c41af4a3'
down_revision = '29d15d666661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personaggi', sa.Column('descrizione', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personaggi', 'descrizione')
    # ### end Alembic commands ###
